#+title: Micro-Compiler
#+description: A very small compiler written in TypeScript to convert lisp-like function calls to C-like function calls adapted from jamiebuilds' "the-super-tiny-compiler".
#+author: Francis Somtochukwu

* Micro-Compiler
This is a super small compiler built in TypeScript to compile lisp-like function calls to C-like function calls. The compilation process typically involves three steps;
1. Parsing
2. Transformation
3. Code Generation.

* Parsing
This is the first stage of code compilation. It involves representing your code in two different ways which are as *Tokens* and as an *Abstract Syntax Tree (AST)*. These are known as Lexical Analysis and Syntatic Analysis respectively.
** Tokenization
According to jamiebuilds, Tokens are an array of tiny little objects that describe an isolated piece of the syntax. They could be numbers, labels, punctuation, operators, whatever.
For the following syntax:

#+BEGIN_SRC lisp
;; lisp
(add 2 (subtract 4 2))
 #+END_SRC

Tokens might look something like this:

#+BEGIN_SRC js
// Tokens
[
      { type: 'paren',  value: '('        },
      { type: 'name',   value: 'add'      },
      { type: 'number', value: '2'        },
      { type: 'paren',  value: '('        },
      { type: 'name',   value: 'subtract' },
      { type: 'number', value: '4'        },
      { type: 'number', value: '2'        },
      { type: 'paren',  value: ')'        },
      { type: 'paren',  value: ')'        },
    ]
 #+END_SRC

This is done by a function called a tokenizer or lexer which
1. Takes in the function call as a string
2. Loops the string and pushes characters, values, operators, et.c to a ~tokens~ array.
3. Returns the array of tokens.
